package com.Clinc_Flow.Clinic.staff;

public enum Permission {
    VIEW_PATIENTS,
    MANAGE_PATIENTS,
    VIEW_APPOINTMENTS,
    MANAGE_APPOINTMENTS,
    VIEW_CALENDAR,
    MANAGE_CALENDAR,
    VIEW_DOCTORS,
    SEND_SMS,
    VIEW_REMINDERS,
    MANAGE_REMINDERS,
    MANAGE_PERMISSIONS,
    VIEW_INVENTORY,
    MANAGE_INVENTORY,
    VIEW_BILLING,
    MANAGE_BILLING,
    VIEW_INCOME
}
